---
all:
  children:
    # ─── Plateforme NOC/SOC ─────────────────────────────────────────────────────
    noc_platform:
      hosts:
        noc-server-01:
          ansible_host: 213.199.42.187
          ansible_user: abdoukarimdiouf
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    # ─── Serveurs Datacenter Principal ─────────────────────────────────────────
    linux_servers:
      children:
        primary_servers:
          hosts:
            monlaptop:
              ansible_host: 192.168.100.151
              site: laptopbureau
            # srvtek06:
            #   ansible_host: 62.84.182.32
            #   site: contabo
            # srvtek04:
            #   ansible_host: 62.84.182.30
            #   site: contabo
            # srvtek05:
            #   ansible_host: 62.84.182.31
            #   site: contabo
            # srvdevil:
            #   ansible_host: 80.241.215.160
            #   site: contabo
            # srv-virt-01:
            #   ansible_host: 192.168.1.120
            #   site: primary

        # ─── Serveurs Site de Repli ─────────────────────────────────────────
        failover_servers:
          hosts:
            #srv-dr-web-01:
            #   ansible_host: 192.168.2.100
            #   site: failover
            # srv-dr-db-01:
            #   ansible_host: 192.168.2.110
            #   site: failover

    # ─── Équipements réseau ─────────────────────────────────────────────────────
    cisco_devices:
      hosts:
        # core-router-01:
        #   ansible_host: 192.168.1.1
        #   ansible_network_os: ios
        # core-router-02:
        #   ansible_host: 192.168.1.2
        #   ansible_network_os: ios
        # dist-switch-01:
        #   ansible_host: 192.168.1.10
        #   ansible_network_os: ios
        # dist-switch-02:
        #   ansible_host: 192.168.1.11
        #   ansible_network_os: ios
        # firewall-01:
        #   ansible_host: 192.168.1.254
        #   ansible_network_os: asa

  vars:
    ansible_user: abdoukarimdiouf
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: 1243
    snmp_auth_password: "{{ vault_snmp_auth_password }}"
    snmp_priv_password: "{{ vault_snmp_priv_password }}"

# NOTE : La clé SSH par groupe a la priorité sur la clé globale ci-dessus.
# noc_platform  → ~/.ssh/id_rsa       (défini au niveau host)
# linux_servers → ~/.ssh/datacenter_key (hérité du global)
# cisco_devices → ~/.ssh/datacenter_key (hérité du global)
